export const categories = [
  { id: 'beach', label: 'Beach', type: 'beach' },
  { id: 'city', label: 'City', type: 'city' },
  { id: 'culture', label: 'Culture', type: 'culture' },
  { id: 'mountain', label: 'Mountain', type: 'mountain' },
];

export const destinations = [
  {
    id: '1',
    name: 'Goa',
    title: 'Goa Beach Escape',
    country: 'India',
    location: 'Goa, India',
    type: 'beach',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    duration: '4 Days / 3 Nights',
    price: 'INR 12,000',
    description: 'Sunlit beaches, Portuguese lanes, seafood shacks, and relaxed coastal nights.',
    bestTime: 'November to February',
    activities: ['Baga Beach', 'Old Goa walk', 'Spice plantation', 'Night market'],
    facilities: ['Hotel', 'Meals', 'Guide', 'Transfers'],
  },
  {
    id: '2',
    name: 'Kyoto',
    title: 'Kyoto Culture Trail',
    country: 'Japan',
    location: 'Kyoto, Japan',
    type: 'culture',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    duration: '5 Days / 4 Nights',
    price: 'INR 35,000',
    description: 'Temple gardens, lantern-lit alleys, tea houses, and gentle historic neighborhoods.',
    bestTime: 'March to May',
    activities: ['Fushimi Inari', 'Arashiyama bamboo walk', 'Tea ceremony', 'Gion evening'],
    facilities: ['Hotel', 'Rail pass', 'Breakfast', 'Guide'],
  },
  {
    id: '3',
    name: 'Swiss Alps',
    title: 'Swiss Alps Retreat',
    country: 'Switzerland',
    location: 'Interlaken, Switzerland',
    type: 'mountain',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    duration: '6 Days / 5 Nights',
    price: 'INR 50,000',
    description: 'Snow peaks, blue lakes, scenic trains, and postcard-perfect alpine towns.',
    bestTime: 'December to March',
    activities: ['Jungfrau day trip', 'Lake cruise', 'Village walk', 'Cable car view'],
    facilities: ['Hotel', 'Train tickets', 'Breakfast', 'Insurance'],
  },
  {
    id: '4',
    name: 'Bali',
    title: 'Bali Island Reset',
    country: 'Indonesia',
    location: 'Bali, Indonesia',
    type: 'beach',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    duration: '5 Days / 4 Nights',
    price: 'INR 28,000',
    description: 'Rice terraces, ocean temples, surf lessons, and slow mornings by the pool.',
    bestTime: 'April to October',
    activities: ['Ubud terraces', 'Uluwatu sunset', 'Surf lesson', 'Spa session'],
    facilities: ['Villa', 'Breakfast', 'Transfers', 'Guide'],
  },
  {
    id: '5',
    name: 'Dubai',
    title: 'Dubai City Lights',
    country: 'UAE',
    location: 'Dubai, UAE',
    type: 'city',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    rating: 4.6,
    duration: '4 Days / 3 Nights',
    price: 'INR 32,000',
    description: 'Skyline views, desert rides, luxury malls, and a polished city break.',
    bestTime: 'November to March',
    activities: ['Burj Khalifa', 'Desert safari', 'Dhow dinner', 'Marina walk'],
    facilities: ['Hotel', 'Transfers', 'Breakfast', 'Tickets'],
  },
  {
    id: '6',
    name: 'Singapore',
    title: 'Singapore Garden City',
    country: 'Singapore',
    location: 'Singapore',
    type: 'city',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    duration: '4 Days / 3 Nights',
    price: 'INR 30,000',
    description: 'Gardens, skyline decks, street food, and polished neighborhoods made for walking.',
    bestTime: 'February to April',
    activities: ['Gardens by the Bay', 'Sentosa', 'Hawker food tour', 'Marina Bay'],
    facilities: ['Hotel', 'Metro card', 'Breakfast', 'Guide'],
  },
];

export const featuredTrips = destinations.slice(0, 4);

export const myTrips = [
  {
    id: '101',
    title: 'Southeast Asia Trail',
    status: 'active',
    startDate: 'May 5, 2026',
    endDate: 'May 18, 2026',
    destinations: ['Bangkok', 'Bali', 'Singapore'],
    totalBudget: 'INR 1,80,000',
    image: destinations[3].image,
    activities: 10,
  },
  {
    id: '102',
    title: 'Europe Explorer',
    status: 'upcoming',
    startDate: 'Jun 15, 2026',
    endDate: 'Jun 28, 2026',
    destinations: ['Paris', 'Rome', 'Swiss Alps'],
    totalBudget: 'INR 3,40,000',
    image: destinations[2].image,
    activities: 8,
  },
  {
    id: '103',
    title: 'Dubai Weekend',
    status: 'completed',
    startDate: 'Feb 1, 2026',
    endDate: 'Feb 4, 2026',
    destinations: ['Dubai'],
    totalBudget: 'INR 92,000',
    image: destinations[4].image,
    activities: 5,
  },
];

export const savedTrips = [destinations[0], destinations[2], destinations[4]];

export const notifications = [
  {
    id: 'n1',
    title: 'Dubai Weekend price dropped',
    message: 'The package you saved is now 12 percent lower than last week.',
    time: '2h ago',
  },
  {
    id: 'n2',
    title: 'Your Bali plan is waiting',
    message: 'Finish traveler details to keep the current villa rate.',
    time: 'Yesterday',
  },
  {
    id: 'n3',
    title: 'New mountain picks',
    message: 'Swiss Alps and Himachal winter routes are trending for December.',
    time: 'May 12',
  },
];

export const profile = {
  name: 'Traveloop Guest',
  email: 'guest@traveloop.app',
  location: 'India',
  travelStyle: 'Balanced explorer',
};
